version: "3"

tasks:
  test:
    desc: "Run tests"
    cmds:
      - go test -coverprofile=cover.out -shuffle=on -race ./...

  integration-test:
    desc: "Run integration tests"
    dotenv: [".env"]
    env:
      INTEGRATION_TEST: on
    cmds:
      - go test -coverprofile=integrataion-cover.out ./...
