name: Run linters

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: ["main"]

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - name: checkout repository
      uses: actions/checkout@v5

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    # https://github.com/golangci/golangci-lint-action
    - name: run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        only-new-issues: true
        args: --timeout=10m
