name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/softprops/action-gh-release
    - name: publish release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
