name: Run tests

on:
  push:
    branches: ["main"]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: ["main"]

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - name: checkout repository
      uses: actions/checkout@v5

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: run tests
      run: go test -race -v ./...
